### PR TITLE
[PKG-2949] tune-sklearn 0.4.6: Rebuild for linux-aarch64 :snowflake:

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
Rebuild for linux-aarch64. Note that I have bumped the build number as I feel like it doesn't hurt.

Also, numpy isn't needed at build time.

Requirements: https://github.com/ray-project/tune-sklearn/blob/v0.4.6/setup.py

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
I removed the staging channel, added a comment about skipping `py>310`, fixed `numpy` in `run`, and removed `scikit-optimize` from `run` because it's a test dependency https://github.com/search?q=repo%3Aray-project%2Ftune-sklearn+scikit-optimize&type=code

**Comment by skupr-anaconda** [comment]
I've added a patch to fix `ray.tune` import https://github.com/ray-project/tune-sklearn/commit/95071b74a1c1ef5495bcba0108960f85d535e9b7. It's deprecated and will be removed in v2.6.0. But the patch doesn't fix `ModuleNotFoundError: No module named 'packaging'` because it will require `ray.air` anyway. I'll add `packaging` to run

**Comment by skupr-anaconda** [comment]
The patch isn't required if we leave `scikit-optimize` in `run`. It's a test dependency but it pulls `packaging` in the test environment and `test/imports` won't fail

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Review by Arishamays1 — APPROVED** [review]
LGTM

**Pull request merged**
